export const studyTopics = [
  {
    href: '/summary/resistance/',
    category: '微生物・薬剤',
    title: '抗菌薬耐性の4つのメカニズム',
    description: '不活化・作用点の変化・修飾・濃度低下と、対策・治療',
    keywords: '抗菌薬 薬剤耐性 耐性菌 メカニズム 機序 不活化 作用点の変化 作用点の修飾 保護 菌体内濃度の低下 メチル化 分解 修飾 βラクタマーゼ ESBL CRE CPE カルバペネマーゼ MRSA VRE PBP2a ポーリン OprD 排出ポンプ 緑膿菌 大腸菌 肺炎桿菌 標的 作用点 膜透過性 保菌 感染症 接触予防策 治療',
  },
  {
    href: '/summary/5moments/',
    category: '手指衛生',
    title: '5moments',
    description: '「前」と「後」でつかむ、5つのタイミング',
    keywords: '手指衛生 5 moments 5moments ファイブモーメンツ 手洗い 患者に触れる前 無菌操作 体液暴露 患者に触れた後 患者周辺環境',
  },
  {
    href: '/summary/disinfection/',
    category: '器材・薬剤',
    title: '消毒薬の水準と使い分け',
    description: 'Spaulding分類と、高・中・低水準の代表薬を整理',
    keywords: '消毒薬 消毒水準 高水準 中水準 低水準 Spaulding スポルディング クリティカル セミクリティカル ノンクリティカル グルタラール グルタルアルデヒド フタラール 過酢酸 次亜塩素酸ナトリウム アルコール ポビドンヨード 第四級アンモニウム塩 クロルヘキシジン 両性界面活性剤 内視鏡',
  },
  {
    href: '/summary/antibiotics/',
    category: '微生物・薬剤',
    title: '抗菌薬の違い',
    description: '作用する場所と、効く菌の範囲を整理',
    keywords: '抗菌薬 抗生物質 抗菌スペクトル 広域 狭域 作用機序 細胞壁 リボソーム 核酸 βラクタム マクロライド キノロン 薬剤感受性 薬剤耐性',
  },
  {
    href: '/summary/gram-stain/',
    category: '微生物・形態',
    title: 'グラム染色 × 菌の形',
    description: '紫／ピンクと、球菌／桿菌から代表菌を見る',
    keywords: 'グラム染色 グラム陽性 グラム陰性 球菌 桿菌 GPC GNC GPR GNR 黄色ブドウ球菌 肺炎球菌 腸球菌 モラクセラ C difficile 大腸菌 肺炎桿菌 インフルエンザ菌 緑膿菌 カンピロバクター 淋菌 紡錘菌 髄膜炎菌 ミレリ菌群',
  },
  {
    href: '/summary/drug-abbreviations/',
    category: '微生物・薬剤',
    title: '抗菌薬の略称と製品名',
    description: '30剤の正式名・製品・効く菌の目安を確認',
    keywords: '抗菌薬 略称 略語 一般名 成分名 製品名 販売名 商品名 抗菌スペクトル 感受性 GPC GNC GPR GNR SBT ABPC AMPC CVA PIPC TAZ CEZ CTM CPZ CTRX CZOP CDTR PI FMOX IPM CS MEPM BIPM DRPM TBPM AMK ABK GM AZM CLDM MINO VCM FOM LZD CPFX LVFX GRNX ST ユナシン サワシリン オーグメンチン ペントシリン ゾシン セファメジン パンスポリン スルペラゾン ロセフィン ファーストシン メイアクト フルマリン チエナム メロペン オメガシン フィニバックス オラペネム ビクリン ハベカシン ゲンタシン ジスロマック ダラシン ミノマイシン バンコマイシン ホスミシン ザイボックス シプロキサン クラビット ジェニナック バクタ',
  },

  { href: '/summary/exposure/', category: '職業感染対策', title: '曝露後の対応ステップ', description: '洗浄 → 報告 → 検査と、予防・経過観察', keywords: '曝露 暴露 針刺し 切創 血液 体液 洗浄 報告 検査 PEP HBIG 72時間' },
  { href: '/summary/cleaning/', category: '環境・器材', title: '洗浄剤と使用時の注意点', description: '汚れを落とし、菌を広げない使い方', keywords: '洗浄剤 洗剤 洗浄 清掃 酵素 播種 拡散 汚染 希釈 濃度 温度 時間 すすぎ 混合 PPE' },
  { href: '/summary/hepatitis-hiv/', category: 'ウイルス・職業感染', title: '肝炎とHIVの比較', description: '経路・ワクチン・治療・感染率と発症の違い', keywords: '肝炎 HBV HCV HAV HIV AIDS A型 B型 C型 感染率 発症率 慢性化 治療 ワクチン 糞口 針刺し 曝露 暴露' },
  { href: '/summary/infection-chain/', category: '感染対策の基本', title: '感染成立の6要素', description: '病原体から宿主まで、つながりと断ち方を図解', keywords: '感染成立 6要素 六要素 ６要素 病原体 病原性 量 宿主 感受性 侵入門戸 伝播経路 チェーン 連鎖' },
  { href: '/summary/bacteria-names/', category: '微生物・菌名', title: '細菌の日本語名・学名・由来', description: '14項目の名前・意味・特徴・感染症をつなげる', keywords: '細菌 日本語 学名 正式名称 名前 菌名 由来 語源 歴史 意味 特徴 感染症 Staphylococcus aureus Streptococcus pneumoniae anginosus Enterococcus Moraxella catarrhalis Neisseria gonorrhoeae meningitidis Clostridioides difficile Escherichia coli Klebsiella Haemophilus influenzae Pseudomonas aeruginosa Campylobacter jejuni Fusobacterium 淋菌 紡錘菌 髄膜炎菌 ミレリ菌群 カンピロバクター 大腸菌 肺炎桿菌 インフルエンザ菌 緑膿菌 肺炎球菌 黄色ブドウ球菌 腸球菌 モラクセラ' },
  { href: '/summary/miller-jones/', category: '微生物・検体', title: 'Miller & Jones分類', description: 'M1〜P3の見分け方と、喀痰評価の歴史', keywords: 'Miller Jones ミラー ジョーンズ ミラージョーンズ 喀痰 分類 M1 M2 P1 P2 P3 膿性 粘液 Geckler ゲックラー 歴史 由来 検体 培養' },
] as const;
