import type { Metadata } from 'next';
import Link from 'next/link';
import StudyPage from '../../components/StudyPage';
import s from '../learning.module.css';
export const metadata: Metadata = { title: '細菌の日本語名・学名・由来 | サクッとまとめ', description: '代表的な細菌14項目の日本語名、学名、語源、形態と感染症をつなげて覚える一覧。' };

const bacteria = [
  { name: '黄色ブドウ球菌', scientific: 'Staphylococcus aureus', group: 'グラム陽性球菌', origin: 'staphylo-＝ブドウの房、coccus＝球菌。aureus＝金色の。', link: '房状の配列と、培養でみられる黄色〜金色の集落に対応します。グラム染色は黄色ではなく紫です。', disease: '皮膚・軟部組織感染、膿瘍、創部感染、菌血症、感染性心内膜炎など。', slugs: ['genus/staphylococcus', 'species/staphylococcus-aureus'] },
  { name: '肺炎球菌', scientific: 'Streptococcus pneumoniae', group: 'グラム陽性球菌', origin: 'Streptococcusは曲がりやすいものを表すstreptosとcoccus（球菌）に由来する属名。pneumoniae＝肺炎の。', link: 'レンサ球菌属ですが、肺炎球菌は主に2個が対になった双球菌として見えます。莢膜を持ちます。属名からすべてを長い連鎖と決めつけません。', disease: '肺炎、中耳炎、副鼻腔炎、髄膜炎、菌血症など。', slugs: ['genus/streptococcus', 'species/streptococcus-pneumoniae'] },
  { name: '腸球菌', scientific: 'Enterococcus spp.', group: 'グラム陽性球菌', origin: 'entero-＝腸、coccus＝球菌。spp.は複数の菌種を表します。', link: '消化管に存在する球菌という名前です。短い連鎖や対でみられます。代表種にEnterococcus faecalisとEnterococcus faeciumがあります。', disease: '尿路感染、菌血症、感染性心内膜炎、腹腔内感染など。', slugs: ['genus/enterococcus'] },
  { name: 'ミレリ菌群（アンギノーサス群）', scientific: 'Streptococcus anginosus group', group: 'グラム陽性球菌 · 3菌種の群', origin: 'Streptococcus anginosus＝咽頭炎などを表すanginaに関係する名、Streptococcus constellatus＝星をちりばめた、Streptococcus intermedius＝中間の。', link: 'この3菌種をまとめた呼び名です。「ミレリ菌」という単一の正式菌種として覚えません。口腔などの常在菌で、膿瘍をつくる性質が臨床上の特徴です。語源だけで膿瘍形成性を説明できるわけではありません。', disease: '歯性感染、肺膿瘍、膿胸、脳膿瘍、肝膿瘍など。', slugs: ['species/streptococcus-anginosus', 'species/streptococcus-constellatus', 'species/streptococcus-intermedius'] },
  { name: 'モラクセラ菌', scientific: 'Moraxella catarrhalis', group: 'グラム陰性球菌', origin: 'Moraxella＝研究者Moraxにちなむ名。catarrhalis＝カタル（粘膜の炎症）に関係する。', link: '属名は人名で、形そのものを示しません。実際の形態は双球菌。種の名前は気道の粘膜炎症と結び付けて覚えられます。', disease: '中耳炎、副鼻腔炎、肺炎、慢性閉塞性肺疾患の増悪など。', slugs: ['genus/moraxella', 'species/moraxella-catarrhalis'] },
  { name: '淋菌', scientific: 'Neisseria gonorrhoeae', group: 'グラム陰性球菌', origin: 'Neisseria＝Albert Neisserにちなむ名。gonorrhoeae＝淋病の。', link: '向かい合う面が平らなくぼみのある双球菌。症状のある男性の尿道分泌物では、好中球内の双球菌が診断上の手掛かりになります。他部位では塗抹だけで判断しません。', disease: '淋菌性尿道炎、子宮頸管炎、骨盤内炎症性疾患、咽頭・直腸感染など。', slugs: ['genus/neisseria', 'species/neisseria-gonorrhoeae'] },
  { name: '髄膜炎菌', scientific: 'Neisseria meningitidis', group: 'グラム陰性球菌', origin: 'Neisseria＝Neisserにちなむ名。meningitidis＝髄膜の炎症（髄膜炎）の。', link: '淋菌と同じ属の双球菌ですが、別の菌種です。鼻咽頭に保菌される場合があり、侵襲性感染で髄膜炎や敗血症を起こします。', disease: '髄膜炎、菌血症・敗血症などの侵襲性髄膜炎菌感染症。', slugs: ['genus/neisseria', 'species/neisseria-meningitidis'] },
  { name: 'クロストリディオイデス・ディフィシル', scientific: 'Clostridioides difficile', group: 'グラム陽性桿菌', origin: 'Clostridioides＝Clostridiumに似たもの。difficile＝難しい（分離・研究が難しかったことに由来）。', link: '「難しい」は本来、治療困難や薬剤耐性という意味ではありません。嫌気性で芽胞を作り、毒素産生株による腸炎が重要です。旧名はClostridium difficileです。', disease: '抗菌薬関連下痢症、偽膜性大腸炎など。', slugs: ['genus/clostridioides', 'species/clostridioides-difficile'] },
  { name: '大腸菌', scientific: 'Escherichia coli', group: 'グラム陰性桿菌', origin: 'Escherichia＝Theodor Escherichにちなむ名。coli＝大腸の。', link: '属名は人名、種の名前は生息部位に由来します。腸に常在する一方、尿路など別の部位に入ると感染症を起こし得ます。すべての株が下痢を起こすわけではありません。', disease: '尿路感染、胆道感染、菌血症。病原性のある一部の株は腸炎。', slugs: ['genus/escherichia', 'species/escherichia-coli'] },
  { name: '肺炎桿菌', scientific: 'Klebsiella pneumoniae', group: 'グラム陰性桿菌', origin: 'Klebsiella＝Edwin Klebsにちなむ名。pneumoniae＝肺炎の。', link: '太く丸みのある桿菌で、厚い莢膜が特徴です。「肺炎」という名前でも肺だけに感染するわけではありません。', disease: '肺炎、尿路感染、胆道感染、菌血症、肝膿瘍など。', slugs: ['genus/klebsiella', 'species/klebsiella-pneumoniae'] },
  { name: 'インフルエンザ菌', scientific: 'Haemophilus influenzae', group: 'グラム陰性桿菌（小型・球桿菌）', origin: 'haemo-＝血液、-philus＝好む。influenzae＝インフルエンザの。', link: '発育に血液由来の成分を必要とします。influenzaeは、かつてインフルエンザの原因と考えられた歴史による名です。インフルエンザウイルスとは異なります。小型で淡く見えることがあり、細胞の破片や粘液に紛れます。', disease: '中耳炎、副鼻腔炎、肺炎。b型などの莢膜株は髄膜炎や菌血症など。', slugs: ['genus/haemophilus', 'species/haemophilus-influenzae'] },
  { name: '緑膿菌', scientific: 'Pseudomonas aeruginosa', group: 'グラム陰性桿菌', origin: 'pseudo-＝偽の、monas＝単位・モナドで、Pseudomonasは「偽のモナド」という語源の属名。aeruginosa＝銅のさび・緑青のような緑色。', link: '色素を作る性質が緑膿菌という日本語名と対応します。菌体がグラム染色で緑になる意味ではありません。湿った場所やバイオフィルムが感染対策で重要です。', disease: '肺炎・慢性気道感染、尿路感染、創部・熱傷感染、菌血症など。', slugs: ['genus/pseudomonas', 'species/pseudomonas-aeruginosa'] },
  { name: 'カンピロバクター', scientific: 'Campylobacter jejuni', group: 'グラム陰性桿菌（湾曲）', origin: 'campylo-＝曲がった、bacter＝棒。jejuni＝空腸の。', link: '湾曲した棒という属名が、そのままカモメの翼状・S字状の形態に対応します。「空腸の」は感染部位を空腸だけに限定する意味ではありません。', disease: '感染性腸炎。感染後にギラン・バレー症候群を生じることがあります。', slugs: ['genus/campylobacter', 'species/campylobacter-jejuni'] },
  { name: '紡錘菌（フソバクテリウム属）', scientific: 'Fusobacterium spp.', group: 'グラム陰性桿菌 · 嫌気性', origin: 'fuso-＝紡錘（糸を紡ぐ道具）、bacterium＝小さな棒。', link: '代表的な形は、中央がふくらみ両端が細くなる紡錘形です。口腔内などに存在する嫌気性菌で、形態には菌種・条件による差があります。', disease: '歯周・歯性感染、誤嚥に関係する肺膿瘍・膿胸など。', slugs: ['genus/fusobacterium'] },
];

export default function BacteriaNames() {
  return <StudyPage title="細菌の日本語名・学名・由来"><div className={s.page}>
    <p className={s.intro}><strong>名前の意味 → 菌の特徴 → 起こす感染症</strong>をつなげると、丸暗記だけに頼らず整理できます。グラム染色で確認する代表的な14項目をまとめました。</p>
    <section className={s.section}><h2>学名の読み方とは</h2><div className={s.flowStrip}><b>Staphylococcus<br /><small>属名</small></b><span aria-hidden="true">＋</span><b>aureus<br /><small>種を区別する名前</small></b><span aria-hidden="true">→</span><b>黄色ブドウ球菌</b></div><p>属名の頭は大文字、後ろは小文字で書きます。<i>Staphylococcus aureus</i>を一度示した後は、<i>S. aureus</i>と省略できます。<strong>spp.はspecies（種）の複数を表す表記</strong>で、単一の菌種名ではありません。</p><p className={s.note}>語源には形・色・生息部位・病名・人名があります。学名だけで感染部位、病原性、薬剤感受性まで決めることはできません。</p></section>
    <nav className={s.jump} aria-label="菌名の一覧">{bacteria.map((b,i) => <a href={`#bacteria-${i}`} key={b.name}>{b.name}</a>)}</nav>
    <section className={s.section}><h2>名前・由来・感染症の一覧</h2><div className={s.nameGrid}>{bacteria.map((b,i) => <article className={s.nameCard} key={b.name} id={`bacteria-${i}`}><span className={s.tag}>{b.group}</span><h3>{b.name}</h3><i lang="la">{b.scientific}</i><dl><dt>学名の由来・意味</dt><dd>{b.origin}</dd><dt>名前と特徴のつながり</dt><dd>{b.link}</dd><dt>引き起こす感染症の例</dt><dd>{b.disease}</dd></dl><p className={s.note}>学名・語源：{b.slugs.map((slug,j) => <span key={slug}>{j ? ' ／ ' : ''}<a href={`https://lpsn.dsmz.de/${slug}`}>{slug.split('/')[1].replaceAll('-', ' ')}</a></span>)}</p></article>)}</div></section>
    <p className={s.callout}>表にある感染症は代表例です。常在・保菌と感染症を区別し、検体の部位、症状、培養などを合わせて判断します。<Link href="/summary/gram-stain/">グラム染色の色と形を図で確認する →</Link></p>
    <section className={s.sources}><h2>出典・確認日</h2><p>2026年9月9日確認。語源・学名は各項目のLPSN（List of Prokaryotic names with Standing in Nomenclature：原核生物の学名データベース）。形態・感染症は以下の出典と照合しています。</p><ol><li><a href="https://www.cdc.gov/pinkbook/hcp/table-of-contents/chapter-8-haemophilus-influenzae.html">CDC：インフルエンザ菌の歴史・性質・感染症</a></li><li><a href="https://www.cdc.gov/meningococcal/hcp/clinical/index.html">CDC：髄膜炎菌感染症</a></li><li><a href="https://www.cdc.gov/std/treatment-guidelines/gonorrhea-adults.htm">CDC：淋菌感染症</a></li><li><a href="https://www.cdc.gov/campylobacter/about/index.html">CDC：カンピロバクター感染症</a></li></ol></section>
  </div></StudyPage>;
}
